### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by marhali** [ocean-tech-ship/ocean-pearl#189]
## TODOs
- [x] update upgradable deps
- [x] check for breaking changes
- [x] test locally (yarn dev)
- [x] test production (nuxt build & nuxt start)
- [ ] test on other machine @Abrom8 

## Wont update
- sass-loader: Nuxt 2.x is not compatible with sass-loader > 10. We will stay on 10.1.2 for now. 
See https://github.com/nuxt/nuxt.js/issues/8771

- node-sass: 6.0.1 is not compatible. See https://github.com/ocean-tech-ship/ocean-pearl/pull/152 / peer to sass-loader
